from typing import Any, Tuple


class Text:
    def get_fontname(self) -> str: ...

    def set_fontname(self, name: str) -> None: ...

    def get_fontweight(self) -> str: ...

    def set_fontweight(self, weight: str) -> None: ...

    def get_weight(self) -> str: ...

    def set_weight(self, weight: str) -> None: ...

    def get_fontstyle(self) -> str: ...

    def set_fontstyle(self, style: str) -> None: ...

    def get_style(self) -> str: ...

    def set_style(self, style: str) -> None: ...

    def get_fontsize(self) -> float: ...

    def set_fontsize(self, size: float | int) -> None: ...

    def get_horizontalalignment(self) -> str: ...

    def set_horizontalalignment(self, align: str) -> None: ...

    def get_ha(self) -> str: ...

    def set_ha(self, align: str) -> None: ...

    def get_va(self) -> str: ...

    def set_color(self, color: Any) -> None: ...

    def get_color(self) -> Any: ...

    def get_text(self) -> str: ...

    def get_rotation(self) -> float | str: ...

    def get_position(self) -> Tuple[float, float]: ...

    pad_offset: float
